### ISSUE TITLE
Still show info for non-signed in instances when some gerrit sites cannot be reached

### ISSUE THREAD

**Issue by jackrosenthal** [sdefresne/gerrit-monitor#7]
Suppose I have two gerrit instances registered (say A and B), and I am only logged into A. I should be able to use the extension without singing into B, maybe just have an error at the top that I need to sign into B.

**Comment by sdefresne** [comment]
I've pushed a new version that includes https://github.com/sdefresne/gerrit-monitor/pull/10. With this version, the extension will try to make a request to the server with CORS disabled which should allow the browser to follow the redirection to the authentication servers and hopefully refresh the authentication.

With this new version, it is possible that you won't see the "Try logging in" message. Could you check when you have time whether the extension is now properly authenticating and not showing up the "Try logging in" error message.

If it is still displayed, I'll investigate how to display the information for the host that can still be reached.

Thank you for your patience.

**Comment by JoeyScarr** [comment]
FWIW (I'm not the OP), I still see the "Try logging in" message. I have one gerrit instance that I visit frequently, and one that I visit infrequently. I'd like Gerrit Monitor to still show me pending CLs for the former without requiring me to log into the latter.

**Comment by sdefresne** [comment]
This should be fixed in version 1.0.4 (which should be deployed soon).

**Comment by jackrosenthal** [comment]
Thanks @sdefresne !! =)
